// FILE: src/pages/MyCourse.tsx
import { useEffect, useState } from "react";
import { useLocation, useNavigate } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Accordion, AccordionItem, AccordionTrigger, AccordionContent } from "@/components/ui/accordion";
import { Download, CheckCircle, Film, BookOpen, Brain, Sparkles, Play, GraduationCap, Layers, Palette, Rocket, Store, Edit, RefreshCw, Eye, Wand2 } from "lucide-react";
import GenerationLoadingScreen from "@/components/GenerationLoadingScreen";
import { motion } from "framer-motion";
import { pollJobStatus as apiPollJobStatus } from "@/api";
import { toast } from "sonner";
import {
    DropdownMenu,
    DropdownMenuContent,
    DropdownMenuItem,
    DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { ChevronDown } from "lucide-react";
import { QuizDisplay } from "@/components/QuizDisplay"; // kept for CourseDetail usage
import SlideViewer from "@/components/SlideViewer";
import { useBrandingGeneration } from "@/hooks/useBrandingGeneration";
import { useCourseDatabase, CourseData } from "@/hooks/useCourseDatabase";
import { CourseEditableHeader } from "@/components/course/CourseEditableHeader";
import { CourseActionsBar } from "@/components/course/CourseActionsBar";
import { PreLaunchChecklist, PreLaunchData } from "@/components/course/PreLaunchChecklist";
import { supabase } from "@/integrations/supabase/client";








interface Lesson {
    lesson_title: string;
    videos?: Array<{ title?: string; script_file?: string } | string>;
    quiz_file?: string;
    workbook_file?: string;
    script_file?: string;
    script_content?: string;
}


interface FullCourse {
    course_title?: string;
    course_description?: string;
    marketing_hook?: string; // Sales pitch for marketplace buyers
    // Backend paths are deprecated - branding is now exclusively via Lovable AI
    logo_path?: string; // @deprecated - ignored, use logo_url instead
    banner_path?: string; // @deprecated - ignored, use banner_url instead
    logo_url?: string; // Generated by Lovable AI
    banner_url?: string; // Generated by Lovable AI
    lessons?: Lesson[];
    zip?: string;
}


// Helper to derive category from course title/description
const deriveCategory = (title?: string, description?: string): string => {
    const text = `${title || ""} ${description || ""}`.toLowerCase();
    const categoryMap: Record<string, string[]> = {
        "Technology": ["coding", "programming", "software", "tech", "ai", "machine learning", "data", "developer", "web", "app", "computer", "python", "javascript"],
        "Business": ["business", "entrepreneur", "startup", "marketing", "sales", "management", "finance", "money", "investing", "leadership"],
        "Creative Arts": ["art", "design", "creative", "music", "photography", "video", "drawing", "painting", "animation", "graphic"],
        "Health & Wellness": ["health", "fitness", "wellness", "yoga", "meditation", "nutrition", "mental", "exercise", "diet", "mindfulness"],
        "Personal Development": ["personal", "productivity", "habits", "growth", "motivation", "mindset", "success", "confidence", "communication", "self"],
        "Language": ["language", "english", "spanish", "french", "german", "japanese", "chinese", "speaking", "writing", "grammar"],
        "Education": ["teaching", "learning", "education", "academic", "study", "course", "training", "skills"],
    };
    
    for (const [category, keywords] of Object.entries(categoryMap)) {
        if (keywords.some(keyword => text.includes(keyword))) {
            return category;
        }
    }
    return "Personal Development"; // Default fallback
};

const MyCourse = () => {
    const navigate = useNavigate();
    const location = useLocation();
    const jobIdFromState = (location.state as any)?.jobId as string | undefined;
    const { generateBranding, isGenerating: isBrandingGenerating } = useBrandingGeneration();
    const { saveCourse, updateCourse, publishCourse, isSaving } = useCourseDatabase();

    // Load wizard data for marketplace publishing
    const [wizardData, setWizardData] = useState(() => {
        const saved = sessionStorage.getItem("coursia_wizard_data");
        return saved ? JSON.parse(saved) : {};
    });

    const [course, setCourse] = useState<FullCourse | null>(() => {
        const saved = sessionStorage.getItem("coursia_full_course");
        return saved ? JSON.parse(saved) : null;
    });
    const [jobId, setJobId] = useState<string | null>(jobIdFromState || null);
    const [status, setStatus] = useState<string | null>(course ? "done" : jobId ? "queued" : null);
    const [progressMsg, setProgressMsg] = useState<string>("Waiting...");
    const [downloading, setDownloading] = useState(false);
    const [publishing, setPublishing] = useState(false);
    const [showPreLaunch, setShowPreLaunch] = useState(false);
    const [generationProgress, setGenerationProgress] = useState(0);
    
    // Database state
    const [savedCourseId, setSavedCourseId] = useState<string | null>(null);
    const [hasUnsavedChanges, setHasUnsavedChanges] = useState(false);
    const [isSavedToDb, setIsSavedToDb] = useState(false);
    const [customPrice, setCustomPrice] = useState<number>(() => {
        const saved = sessionStorage.getItem("coursia_preview_price");
        return saved ? parseFloat(saved) : 49.00;
    });
    const [category, setCategory] = useState<string>(() => {
        return deriveCategory(course?.course_title, course?.course_description);
    });
    const [audienceLevel, setAudienceLevel] = useState<string>(() => {
        return wizardData.audienceLevel || "Intermediate";
    });


    const [activeScriptTitle, setActiveScriptTitle] = useState<string | null>(null);
    const [activeScriptContent, setActiveScriptContent] = useState<string | null>(null);

    const [openSlidesForLesson, setOpenSlidesForLesson] = useState<string | null>(null);

    // Map status strings to progress percentages
    const statusToProgress = (s: string): number => {
        const map: Record<string, number> = {
            queued: 5, starting: 8, processing: 12, analyzing: 15,
            structuring: 25, generating: 35, scripts: 45, generating_scripts: 45,
            running: 50, quizzes: 60, creating_quizzes: 60,
            workbooks: 72, building_workbooks: 72,
            branding: 82, creating_branding: 82,
            polishing: 90, finalizing: 95, done: 100,
        };
        const lower = s.toLowerCase();
        for (const [key, val] of Object.entries(map)) {
            if (lower.includes(key)) return val;
        }
        return 10;
    };

    // Poll for job completion when we have a jobId but no course yet
    useEffect(() => {
        if (!jobId || course) return;

        let cancelled = false;

        const poll = async () => {
            try {
                setStatus("processing");
                setGenerationProgress(5);
                const result = await apiPollJobStatus(jobId, (s) => {
                    if (!cancelled) {
                        setStatus(s);
                        setProgressMsg(s);
                        setGenerationProgress(statusToProgress(s));
                    }
                });

                if (!cancelled && result) {
                    setGenerationProgress(100);
                    setCourse(result);
                    setStatus("done");
                    sessionStorage.setItem("coursia_full_course", JSON.stringify(result));
                    toast.success("Course generated successfully!");
                }
            } catch (err) {
                if (!cancelled) {
                    console.error("Polling failed:", err);
                    setStatus("error");
                    toast.error("Course generation failed. Please try again.");
                }
            }
        };

        poll();

        return () => { cancelled = true; };
    }, [jobId, course]);

    // Auto-generate fallback branding if course has no logo/banner
    useEffect(() => {
        if (!course || isBrandingGenerating) return;
        if (course.logo_url && course.banner_url) return;
        
        const autoGenerate = async () => {
            const result = await generateBranding({
                course_title: course.course_title || "Course",
                course_description: course.course_description,
                style: "modern",
            });
            if (result.logo_url || result.banner_url) {
                const updated = {
                    ...course,
                    logo_url: result.logo_url || course.logo_url,
                    banner_url: result.banner_url || course.banner_url,
                };
                setCourse(updated);
                sessionStorage.setItem("coursia_full_course", JSON.stringify(updated));
                setHasUnsavedChanges(true);
            }
        };
        autoGenerate();
    }, [course?.course_title, !course?.logo_url || !course?.banner_url]);

    // Slides are now generated via Supabase edge function
    const handleViewSlides = (lessonId: string, scriptText?: string) => {
        setActiveScriptContent(scriptText || activeScriptContent);
        setOpenSlidesForLesson(lessonId);
    };

    const toURL = (path?: string) => {
        if (!path) return "";
        return path
            .replace(/^.*generated[\\/]/, "http://127.0.0.1:8000/generated/")
            .replace(/\\/g, "/");
    };

    const handleDownloadZip = async () => {
        if (!course?.zip) {
            alert("No ZIP available for download.");
            return;
        }
        try {
            setDownloading(true);
            const res = await fetch(course.zip);
            if (!res.ok) throw new Error("Download failed");
            const blob = await res.blob();
            const url = URL.createObjectURL(blob);
            const a = document.createElement("a");
            a.href = url;
            a.download = `${(course.course_title || "course").replace(/\s+/g, "_")}.zip`;
            document.body.appendChild(a);
            a.click();
            a.remove();
            URL.revokeObjectURL(url);
        } catch (e) {
            console.error(e);
            alert("Download failed — check console.");
        } finally {
            setDownloading(false);
        }
    };


    const handleViewScript = async (title: string, path?: string, lessonIndex?: number) => {
        if (!path) return alert("No script file found.");

        try {
            const res = await fetch(toURL(path));
            if (!res.ok) throw new Error("Failed to load script file");
            const text = await res.text();

            sessionStorage.setItem("coursia_edit_script", text);
            navigate(`/my-course/script?title=${encodeURIComponent(title)}&lessonIndex=${lessonIndex ?? 0}&courseId=${jobId || ""}`);
        } catch (err) {
            console.error(err);
            alert("Failed to load script — check console.");
        }
    };


    const handleViewQuiz = async (title: string, path?: string, lessonIndex?: number) => {
        if (!path) return alert("No quiz file found.");
        try {
            const res = await fetch(toURL(path));
            if (!res.ok) throw new Error("Failed to load quiz file");
            const text = await res.text();
            let quizData = JSON.parse(text);

            // Check if there are saved edits for this lesson
            if (lessonIndex !== undefined) {
                const quizUpdates = JSON.parse(sessionStorage.getItem("coursia_quiz_updates") || "{}");
                if (quizUpdates[lessonIndex]) {
                    quizData = quizUpdates[lessonIndex];
                }
            }

            // Store quiz data for the editor page
            sessionStorage.setItem("coursia_edit_quiz", JSON.stringify(quizData));
            navigate(`/my-course/quiz?title=${encodeURIComponent(title)}&lessonIndex=${lessonIndex ?? 0}`);
        } catch (err) {
            console.error(err);
            alert("Failed to load quiz — check console.");
        }
    };


    const handleViewWorkbook = async (title: string, path?: string, lessonIndex?: number) => {
        if (!path) return alert("No workbook file found.");
        try {
            const res = await fetch(toURL(path));
            if (!res.ok) throw new Error("Failed to load workbook file");
            const text = await res.text();

            sessionStorage.setItem("coursia_edit_workbook", text);
            navigate(`/my-course/workbook?title=${encodeURIComponent(title)}&lessonIndex=${lessonIndex ?? 0}&courseId=${jobId || ""}`);
        } catch (err) {
            console.error(err);
            alert("Failed to load workbook — check console.");
        }
    };


    // Show loading screen when generating (status is not done and we have a jobId)
    const isGenerating = jobId && status !== "done" && status !== "error";

    return (
        <div className="min-h-screen bg-background">
            {/* Generation Loading Screen */}
            <GenerationLoadingScreen
                isOpen={!!isGenerating}
                currentStep={status || "analyzing"}
                progress={generationProgress}
                title="Generating Your Full Course"
                subtitle="Creating scripts, quizzes, workbooks, and more..."
            />

            {/* Animated background orbs */}
            <div className="fixed inset-0 overflow-hidden pointer-events-none">
                <div className="absolute -top-40 -right-40 w-96 h-96 bg-primary/10 rounded-full blur-3xl animate-float" />
                <div className="absolute top-1/2 -left-40 w-80 h-80 bg-secondary/10 rounded-full blur-3xl animate-float" style={{ animationDelay: "1s" }} />
                <div className="absolute -bottom-20 right-1/3 w-72 h-72 bg-accent/10 rounded-full blur-3xl animate-float" style={{ animationDelay: "2s" }} />
            </div>

            <div className="relative z-10 max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8 space-y-8">
                {/* Editable Course Header */}
                <CourseEditableHeader
                    title={course?.course_title || "Your Course"}
                    description={course?.course_description}
                    marketingHook={course?.marketing_hook}
                    category={category}
                    audienceLevel={audienceLevel}
                    outcome={wizardData.outcome}
                    lessonsCount={course?.lessons?.length || 0}
                    price={customPrice}
                    bannerUrl={course?.banner_url}
                    isSaving={isSaving}
                    onUpdate={async (updates) => {
                        if (!course) return;
                        
                        // Update local state
                        const updatedCourse = { ...course };
                        if (updates.title) updatedCourse.course_title = updates.title;
                        if (updates.description !== undefined) updatedCourse.course_description = updates.description;
                        if (updates.marketing_hook !== undefined) updatedCourse.marketing_hook = updates.marketing_hook;
                        if (updates.category) setCategory(updates.category);
                        if (updates.audience_level) setAudienceLevel(updates.audience_level);
                        if (updates.custom_price !== undefined) {
                            setCustomPrice(updates.custom_price);
                            sessionStorage.setItem("coursia_preview_price", updates.custom_price.toString());
                        }
                        
                        setCourse(updatedCourse);
                        sessionStorage.setItem("coursia_full_course", JSON.stringify(updatedCourse));
                        setHasUnsavedChanges(true);
                        
                        // If saved to DB, update there too
                        if (savedCourseId) {
                            await updateCourse(savedCourseId, {
                                ...updates,
                                title: updates.title || course.course_title || "Untitled",
                            });
                        }
                    }}
                />

                {/* Actions & Stats Bar */}
                <CourseActionsBar
                    lessonsCount={course?.lessons?.length || 0}
                    videosCount={course?.lessons?.reduce((acc, l) => acc + (l.videos?.length || 0), 0) || 0}
                    quizzesCount={course?.lessons?.filter(l => l.quiz_file).length || 0}
                    isBrandingGenerating={isBrandingGenerating}
                    isPublishing={publishing}
                    onRegenerateBranding={async () => {
                        if (!course) return;
                        const result = await generateBranding({
                            course_title: course.course_title || "Course",
                            course_description: course.course_description,
                            style: "modern",
                        });
                        if (result.logo_url || result.banner_url) {
                            const updated = {
                                ...course,
                                logo_url: result.logo_url || course.logo_url,
                                banner_url: result.banner_url || course.banner_url,
                            };
                            setCourse(updated);
                            sessionStorage.setItem("coursia_full_course", JSON.stringify(updated));
                            setHasUnsavedChanges(true);
                        }
                    }}
                    onPublish={() => {
                        if (!course) {
                            toast.error("No course data yet to publish.");
                            return;
                        }
                        setShowPreLaunch(true);
                    }}
                />

                {/* Pre-Launch Checklist Dialog */}
                <PreLaunchChecklist
                    open={showPreLaunch}
                    onOpenChange={setShowPreLaunch}
                    isPublishing={publishing}
                    initialData={{
                        title: course?.course_title || "Untitled Course",
                        description: course?.course_description,
                        category,
                        audienceLevel,
                        price: customPrice,
                        marketingHook: course?.marketing_hook,
                        lessonsCount: course?.lessons?.length || 0,
                        videosCount: course?.lessons?.reduce((acc, l) => acc + (l.videos?.length || 0), 0) || 0,
                        quizzesCount: course?.lessons?.filter(l => l.quiz_file).length || 0,
                        hasLogo: !!course?.logo_url,
                        hasBanner: !!course?.banner_url,
                    }}
                    onConfirmPublish={async (data: PreLaunchData) => {
                        if (!course) return;
                        
                        const { data: { user } } = await supabase.auth.getUser();
                        if (!user) {
                            toast.error("Please sign in to publish your course");
                            navigate("/auth");
                            return;
                        }
                        
                        setPublishing(true);

                        // Apply pre-launch data to course
                        const updatedCourse = {
                            ...course,
                            course_title: data.title,
                            course_description: data.description,
                            marketing_hook: data.marketingHook,
                        };
                        setCourse(updatedCourse);
                        setCategory(data.category);
                        setAudienceLevel(data.audienceLevel);
                        setCustomPrice(data.price);

                        // Save to database
                        const courseData: CourseData = {
                            title: data.title,
                            description: data.description,
                            category: data.category,
                            outcome: wizardData.outcome,
                            target_audience: wizardData.audience,
                            audience_level: data.audienceLevel,
                            course_size: wizardData.courseSize,
                            materials: wizardData.materials,
                            links: wizardData.links,
                            logo_url: course.logo_url,
                            banner_url: course.banner_url,
                            custom_price: data.price,
                            marketing_hook: data.marketingHook,
                            lessons: course.lessons,
                            status: "published",
                            published_at: new Date().toISOString(),
                        };
                        
                        let dbCourseId = savedCourseId;
                        
                        if (savedCourseId) {
                            await updateCourse(savedCourseId, { ...courseData, status: "published", published_at: new Date().toISOString() });
                        } else {
                            const saved = await saveCourse({ ...courseData, status: "published" });
                            if (saved?.id) {
                                dbCourseId = saved.id;
                                setSavedCourseId(saved.id);
                                setIsSavedToDb(true);
                            }
                        }

                        // Gather quizzes and workbooks for localStorage marketplace
                        const quizzes: any[] = [];
                        const workbooks: string[] = [];

                        for (const lesson of course.lessons || []) {
                            if (lesson.quiz_file) {
                                try {
                                    const res = await fetch(toURL(lesson.quiz_file));
                                    if (res.ok) {
                                        const quizData = await res.json();
                                        quizzes.push(quizData);
                                    } else quizzes.push(null);
                                } catch { quizzes.push(null); }
                            } else quizzes.push(null);

                            if (lesson.workbook_file) {
                                try {
                                    const res = await fetch(toURL(lesson.workbook_file));
                                    if (res.ok) {
                                        const workbookText = await res.text();
                                        workbooks.push(workbookText);
                                    } else workbooks.push("");
                                } catch { workbooks.push(""); }
                            } else workbooks.push("");
                        }

                        const publishedCourse = {
                            id: dbCourseId || `user-${Date.now()}`,
                            title: data.title,
                            instructor: "You",
                            rating: 5.0,
                            reviews: 0,
                            price: data.price,
                            duration: `${course.lessons?.length || 1} lessons`,
                            students: 0,
                            category: data.category,
                            level: data.audienceLevel as "Beginner" | "Intermediate" | "Advanced",
                            image: course.banner_url || "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=800&q=80",
                            featured: true,
                            isUserCourse: true,
                            wizardData: {
                                audience: wizardData.audience,
                                audienceLevel: data.audienceLevel,
                                outcome: wizardData.outcome,
                                courseSize: wizardData.courseSize,
                            },
                            courseData: { ...updatedCourse, quizzes, workbooks },
                        };

                        const existing = JSON.parse(localStorage.getItem("coursia_published_courses") || "[]");
                        const filtered = existing.filter((c: any) => c.id !== publishedCourse.id);
                        filtered.unshift(publishedCourse);
                        localStorage.setItem("coursia_published_courses", JSON.stringify(filtered));

                        setPublishing(false);
                        setShowPreLaunch(false);
                        setHasUnsavedChanges(false);
                        toast.success("🎉 Course published to marketplace!");
                        setTimeout(() => navigate("/marketplace"), 800);
                    }}
                />


                {/* Main Content Section */}
                <motion.section
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ delay: 0.7, duration: 0.5 }}
                    className="grid grid-cols-1 lg:grid-cols-3 gap-8"
                >
                    {/* Lessons Column */}
                    <main className="lg:col-span-2 space-y-4">
                        <div className="flex items-center gap-3 mb-6">
                            <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-primary/20 to-secondary/20 flex items-center justify-center border border-primary/20">
                                <Layers className="w-5 h-5 text-primary" />
                            </div>
                            <div>
                                <h2 className="text-xl font-semibold">Course Content</h2>
                                <p className="text-sm text-muted-foreground">{course?.lessons?.length || 0} lessons available</p>
                            </div>
                        </div>

                        {course?.lessons?.length ? (
                            <Accordion type="single" collapsible className="w-full space-y-3">
                                {course.lessons.map((lesson, li) => (
                                    <motion.div
                                        key={li}
                                        initial={{ opacity: 0, x: -20 }}
                                        animate={{ opacity: 1, x: 0 }}
                                        transition={{ delay: 0.1 * li, duration: 0.4 }}
                                    >
                                        <AccordionItem
                                            value={`lesson-${li}`}
                                            className="glass-strong border border-white/10 rounded-2xl overflow-hidden hover:shadow-glass transition-all duration-300"
                                        >
                                            <AccordionTrigger className="px-5 py-4 hover:no-underline group">
                                                <div className="flex items-center gap-4 text-left w-full">
                                                    <div className="w-12 h-12 rounded-xl bg-gradient-to-br from-primary/20 to-secondary/20 flex items-center justify-center border border-primary/20 shrink-0 group-hover:scale-105 transition-transform">
                                                        <span className="text-lg font-bold gradient-text">{li + 1}</span>
                                                    </div>
                                                    <div className="flex-1 min-w-0">
                                                        <span className="font-semibold text-base block truncate">{lesson.lesson_title || `Lesson ${li + 1}`}</span>
                                                        <div className="flex items-center gap-3 mt-1">
                                                            <span className="text-xs text-muted-foreground flex items-center gap-1">
                                                                <Film className="w-3 h-3" /> {lesson.videos?.length || 0} Videos
                                                            </span>
                                                            {lesson.quiz_file && (
                                                                <span className="text-xs text-emerald-500 flex items-center gap-1">
                                                                    <Brain className="w-3 h-3" /> Quiz
                                                                </span>
                                                            )}
                                                            {lesson.workbook_file && (
                                                                <span className="text-xs text-secondary flex items-center gap-1">
                                                                    <BookOpen className="w-3 h-3" /> Workbook
                                                                </span>
                                                            )}
                                                        </div>
                                                    </div>
                                                </div>
                                            </AccordionTrigger>

                                            <AccordionContent className="px-5 pb-5 pt-2 space-y-5">
                                                {/* Videos Grid */}
                                                {lesson.videos?.length ? (
                                                    <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                                                        {lesson.videos.map((v, vi) => {
                                                            const video = typeof v === "string"
                                                                ? { title: `Video ${vi + 1}`, script_file: v }
                                                                : v;

                                                            return (
                                                                <div
                                                                    key={vi}
                                                                    className="group p-4 rounded-xl glass border border-white/10 hover:border-primary/30 transition-all duration-300 hover:shadow-md"
                                                                >
                                                                    <div className="flex items-start gap-3">
                                                                        <div className="w-10 h-10 rounded-lg bg-primary/10 flex items-center justify-center shrink-0 group-hover:bg-primary/20 transition-colors">
                                                                            <Play className="w-4 h-4 text-primary" />
                                                                        </div>
                                                                        <div className="flex-1 min-w-0">
                                                                            <div className="font-medium text-sm truncate">{video.title || `Video ${vi + 1}`}</div>
                                                                            <Button
                                                                                size="sm"
                                                                                variant="ghost"
                                                                                className="mt-2 h-7 text-xs px-2 hover:bg-primary/10"
                                                                                onClick={() => handleViewScript(video.title || `Video ${vi + 1}`, video.script_file, li)}
                                                                            >
                                                                                <Film className="w-3 h-3 mr-1" /> View Script
                                                                            </Button>
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                            );
                                                        })}
                                                    </div>
                                                ) : (
                                                    <div className="text-sm text-muted-foreground text-center py-4">No videos available.</div>
                                                )}

                                                {/* Quiz & Workbook */}
                                                <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                                                    {lesson.quiz_file && (
                                                        <div className="p-4 rounded-xl bg-gradient-to-br from-emerald-500/10 to-teal-500/10 border border-emerald-500/20">
                                                            <div className="flex items-center gap-2 mb-3">
                                                                <Brain className="w-5 h-5 text-emerald-500" />
                                                                <span className="font-semibold text-sm">Quiz</span>
                                                            </div>
                                                            <Button
                                                                size="sm"
                                                                className="w-full bg-emerald-500/20 hover:bg-emerald-500/30 text-emerald-700 dark:text-emerald-300 border border-emerald-500/30"
                                                                onClick={() => handleViewQuiz(lesson.lesson_title || "Quiz", lesson.quiz_file, li)}
                                                            >
                                                                <Edit className="w-3 h-3 mr-1" /> Edit Quiz
                                                            </Button>
                                                        </div>
                                                    )}

                                                    {lesson.workbook_file && (
                                                        <div className="p-4 rounded-xl bg-gradient-to-br from-secondary/10 to-purple-500/10 border border-secondary/20">
                                                            <div className="flex items-center gap-2 mb-3">
                                                                <BookOpen className="w-5 h-5 text-secondary" />
                                                                <span className="font-semibold text-sm">Workbook</span>
                                                            </div>
                                                            <Button
                                                                size="sm"
                                                                className="w-full bg-secondary/20 hover:bg-secondary/30 text-secondary-foreground border border-secondary/30"
                                                                onClick={() => handleViewWorkbook(lesson.lesson_title || "Workbook", lesson.workbook_file, li)}
                                                            >
                                                                Open Workbook
                                                            </Button>
                                                        </div>
                                                    )}

                                                </div>
                                            </AccordionContent>
                                        </AccordionItem>
                                    </motion.div>
                                ))}
                            </Accordion>
                        ) : (
                            <div className="glass-strong border border-white/10 rounded-2xl p-12 text-center">
                                <div className="w-16 h-16 mx-auto mb-4 rounded-2xl bg-primary/10 flex items-center justify-center animate-pulse">
                                    <Sparkles className="w-8 h-8 text-primary" />
                                </div>
                                <h3 className="text-lg font-semibold mb-2">Generating Your Course</h3>
                                <p className="text-muted-foreground">Please wait while we create your content...</p>
                            </div>
                        )}
                    </main>

                    {/* Sidebar */}
                    <aside className="space-y-6">
                        {/* Premium Logo Card */}
                        <Card className="glass-strong border border-white/10 overflow-hidden">
                            <div className="p-6 text-center">
                                {course?.logo_url ? (
                                    <motion.div
                                        initial={{ scale: 0.9, opacity: 0 }}
                                        animate={{ scale: 1, opacity: 1 }}
                                        transition={{ duration: 0.5 }}
                                        className="relative"
                                    >
                                        <div className="w-32 h-32 mx-auto rounded-2xl overflow-hidden shadow-elevated ring-4 ring-white/10">
                                            <img
                                                src={course.logo_url}
                                                alt="Course logo"
                                                className="w-full h-full object-contain bg-card"
                                            />
                                        </div>
                                        <p className="text-xs text-muted-foreground mt-4">
                                            Course Logo
                                        </p>
                                    </motion.div>
                                ) : isBrandingGenerating ? (
                                    <div className="w-32 h-32 mx-auto rounded-2xl bg-muted/20 flex items-center justify-center border border-white/10">
                                        <RefreshCw className="w-8 h-8 text-primary animate-spin" />
                                    </div>
                                ) : (
                                    <div className="w-32 h-32 mx-auto rounded-2xl bg-gradient-to-br from-primary/10 to-secondary/10 flex items-center justify-center border border-white/10">
                                        <GraduationCap className="w-12 h-12 text-primary/50" />
                                    </div>
                                )}
                            </div>
                        </Card>

                        {/* Tips Card */}
                        <Card className="glass-strong border border-white/10 p-5">
                            <div className="flex items-center gap-3 mb-4">
                                <div className="w-8 h-8 rounded-lg bg-gradient-to-br from-amber-500/20 to-orange-500/20 flex items-center justify-center">
                                    <Sparkles className="w-4 h-4 text-amber-500" />
                                </div>
                                <h3 className="font-semibold">Quick Tips</h3>
                            </div>

                            <div className="space-y-3">
                                <div className="flex items-start gap-3 text-sm">
                                    <div className="w-6 h-6 rounded-full bg-primary/10 flex items-center justify-center shrink-0 mt-0.5">
                                        <Download className="w-3 h-3 text-primary" />
                                    </div>
                                    <span className="text-muted-foreground">Download ZIP for your complete course package</span>
                                </div>
                                <div className="flex items-start gap-3 text-sm">
                                    <div className="w-6 h-6 rounded-full bg-emerald-500/10 flex items-center justify-center shrink-0 mt-0.5">
                                        <CheckCircle className="w-3 h-3 text-emerald-500" />
                                    </div>
                                    <span className="text-muted-foreground">Publish to share your course online</span>
                                </div>
                                <div className="flex items-start gap-3 text-sm">
                                    <div className="w-6 h-6 rounded-full bg-secondary/10 flex items-center justify-center shrink-0 mt-0.5">
                                        <Edit className="w-3 h-3 text-secondary" />
                                    </div>
                                    <span className="text-muted-foreground">Use Edit to adjust and regenerate content</span>
                                </div>
                            </div>
                        </Card>

                        {/* Stats Card */}
                        {course?.lessons?.length && (
                            <Card className="glass-strong border border-white/10 p-5">
                                <h3 className="font-semibold mb-4">Course Overview</h3>
                                <div className="grid grid-cols-2 gap-3">
                                    <div className="text-center p-3 rounded-xl bg-primary/5 border border-primary/10">
                                        <div className="text-2xl font-bold gradient-text">{course.lessons.length}</div>
                                        <div className="text-xs text-muted-foreground">Lessons</div>
                                    </div>
                                    <div className="text-center p-3 rounded-xl bg-secondary/5 border border-secondary/10">
                                        <div className="text-2xl font-bold text-secondary">{course.lessons.reduce((acc, l) => acc + (l.videos?.length || 0), 0)}</div>
                                        <div className="text-xs text-muted-foreground">Videos</div>
                                    </div>
                                    <div className="text-center p-3 rounded-xl bg-emerald-500/5 border border-emerald-500/10">
                                        <div className="text-2xl font-bold text-emerald-500">{course.lessons.filter(l => l.quiz_file).length}</div>
                                        <div className="text-xs text-muted-foreground">Quizzes</div>
                                    </div>
                                    <div className="text-center p-3 rounded-xl bg-amber-500/5 border border-amber-500/10">
                                        <div className="text-2xl font-bold text-amber-500">{course.lessons.filter(l => l.workbook_file).length}</div>
                                        <div className="text-xs text-muted-foreground">Workbooks</div>
                                    </div>
                                </div>
                            </Card>
                        )}
                    </aside>
                </motion.section>
            </div>
            {/* Script is now a full-page view - no dialog needed */}




            {/* Quiz is now a full-page editor - no dialog needed */}


            {/* Workbook is now a full-page view - no dialog needed */}


            {/* --- Slide Viewer Modal --- */}
            <SlideViewer
                open={!!openSlidesForLesson}
                onOpenChange={(v) => { if (!v) setOpenSlidesForLesson(null); }}
                lessonId={openSlidesForLesson}
                scriptText={activeScriptContent || undefined}
                lessonTitle={activeScriptTitle || undefined}
            />

            {/* Video with Slides is now on the script page */}
        </div >
    );
};


export default MyCourse;